### ISSUE TITLE
docker container out of sync with conda-lock.yml

### ISSUE THREAD

**Issue by beckermr** [regro/cf-graph-countyfair-2025-07-18#35]
Right now the docker container is out of sync with the conda-lock.yml (since I moved the relock script to this repo but left the container in cf-scripts). We need to do fix it. Here are some ideas:

- rebuild the container for certain package updates (conda-forge-feedstock-ops, conda, conda-build, etc.) 
- move the container build to this repo
- something else?

https://github.com/conda-forge/conda-forge-feedstock-ops/issues/23

cc @h-vetinari

**Comment by h-vetinari** [comment]
Which container are we talking about?

In any case, we could _probably_ do a `diff` of the `conda-lock.yml` baked (implicitly?) into the container vs. the other one (which lives where?), and if there's a difference, trigger a container rebuild?

**Comment by beckermr** [comment]
One of the ones the bot uses and yes. The relock script outputs what it changes and we can add a rebuild on that.

**Comment by beckermr** [comment]
The sync has been working for a bit now. Closing this.
